### ISSUE TITLE
Angular bind polymer throws exceptions with ng-if or ui-router

### ISSUE THREAD

**Issue by JWGmeligMeyling** [eee-c/angular-bind-polymer#14]
When I use the bind polymer directive on elements hidden with ng-if and for example indirectly via ui-router, I get the following exception:

```
 TypeError: Cannot read property 'match' of undefined
    at link (http://localhost:8080/bower_components/angular-bind-polymer/angular_bind_polymer.js:11:43)
    at Z (http://localhost:8080/bower_components/angular/angular.min.js:70:149)
    at A (http://localhost:8080/bower_components/angular/angular.min.js:59:203)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:51:299)
    at A (http://localhost:8080/bower_components/angular/angular.min.js:59:147)
    at $get.c (http://localhost:8080/bower_components/angular/angular.min.js:66:333)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:51:299)
    at http://localhost:8080/bower_components/angular/angular.min.js:50:415
    at $get.h (http://localhost:8080/bower_components/angular/angular.min.js:52:283)
    at l (http://localhost:8080/bower_components/angular/angular.min.js:56:293)
```

**Comment by JWGmeligMeyling** [comment]
Seems the problem is gone when I remove an `ng-disabled` directive. Maybe this has something to do with priority?

**Comment by eee-c** [comment]
That seems reasonable to me. Would it be possible to send a pull request with a test or a modified [index.html](https://github.com/eee-c/angular-bind-polymer/blob/master/index.html) that demonstrates the problem?

**Comment by JWGmeligMeyling** [comment]
I've added a checkbox that is bound to the ngif on the container with the old example. After the first hide, the example is broken.
```html
<!doctype html>
<html>
  <head>
    <title>Smoke Test</title>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type">

    <!-- 1. Load Polymer before any code that touches the DOM. -->
    <script src="bower_components/webcomponentsjs/webcomponents.js"></script>

    <!-- 2. Load Angular and angular-bind-polymer -->
    <script src="bower_components/angular/angular.min.js"></script>
    <script src="angular_bind_polymer.js"></script>

    <!-- 3. Establish the Angular application -->
    <script>
      angular.module('smokeTest', [
       'eee-c.angularBindPolymer'
      ]);
    </script>

    <!-- 4. Load Polymer component(s) -->
    <link rel="import" href="test/x-double.html">
  </head>
  <body ng-app="smokeTest">
    <div class="container" ng-init="abba = true">
      <h1>Smoke Test: angular-bind-polymer</h1>

      <label>
        <input type="checkbox" ng-model="abba">
        Hide the polymer element using <code>ngIf</code>. Currently <span ng-bind="abba ? 'hided' : 'shown'"></span>
      </label>

      <div ng-if="abba">
      <p>
        in:<br>
        <input type=text value="6" ng-model="in">
      </p>
      <p>
        out:
        <pre ng-bind="doubled"></pre>
      </p>
        <x-double bind-polymer in="{{in}}" out="{{doubled}}"></x-double>
      </div>
    </div>
  </body>
</html>
```

**Comment by JWGmeligMeyling** [comment]
Created a PR for how I resolved this issue
